version: '2'
services:
  backend:
    build: backend
    command: scripts/wait-for-it.sh postgres:5432 -- python manage.py docker_start
    ports:
      - 8000:8000
    links:
      - postgres
    volumes:
      - ./backend/edegal:/usr/src/app/edegal
      - media:/usr/src/app/media
    environment:
      DEBUG: 1
      PYTHONUNBUFFERED: 1
      DATABASE_URL: psql://edegal:edegal@postgres/edegal
      ALLOWED_HOSTS: '*'
  frontend:
    build: frontend
    ports:
      - 3000:3000
    links:
      - backend
    volumes:
      - ./frontend/src:/usr/src/app/src
    environment:
      EDEGAL_BACKEND_URL: http://backend:8000
  postgres:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: edegal
      POSTGRES_PASSWORD: edegal
      POSTGRES_DB: edegal
volumes:
  postgres-data: {}
  media: {}
